# Generated by Django 5.1.6 on 2025-10-22 11:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('creation_date_time', models.DateTimeField(auto_now_add=True)),
                ('modification_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulation_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulation_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_number', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('creation_date_time', models.DateTimeField(auto_now_add=True)),
                ('modification_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_modified', to=settings.AUTH_USER_MODEL)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='simulation', to='main.simulation')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studienr', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=255)),
                ('campus', models.CharField(max_length=255)),
                ('subscription_key', models.CharField(max_length=255, unique=True)),
                ('market_member_num', models.IntegerField(default=0)),
                ('simulation_number', models.BigIntegerField(blank=True, null=True)),
                ('creation_date_time', models.DateTimeField(auto_now_add=True)),
                ('modification_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('creation_date_time', models.DateTimeField(auto_now_add=True)),
                ('modification_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date_time', models.DateTimeField(auto_now_add=True)),
                ('modification_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_member_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_member_modified', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='student_team_member', to='main.student')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='team_team_member', to='main.team')),
            ],
        ),
        migrations.CreateModel(
            name='StudentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.BigIntegerField()),
                ('company', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('go_venture_subscription_key', models.CharField(max_length=255, unique=True)),
                ('simulation_number', models.CharField(max_length=255)),
                ('rubric_score_percentage', models.IntegerField(default=0)),
                ('balanced_score_percentage', models.IntegerField(default=0)),
                ('participation_percentage', models.IntegerField(default=0)),
                ('participation_total', models.IntegerField(default=0)),
                ('participation_in', models.IntegerField(default=0)),
                ('rank_score_percentage', models.IntegerField(default=0)),
                ('hr_score_percentage', models.IntegerField(default=0)),
                ('ethics_score_percentage', models.IntegerField(default=0)),
                ('competency_quiz_percentage', models.IntegerField(default=0)),
                ('team_evaluation_percentage', models.IntegerField(default=0)),
                ('period_joined', models.IntegerField(default=0)),
                ('tutorial_quiz_percentage', models.IntegerField(null=True)),
                ('creation_date_time', models.DateTimeField(auto_now_add=True)),
                ('modification_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_scores_created', to=settings.AUTH_USER_MODEL)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='market_scores', to='main.market')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_scores_modified', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='student_scores', to='main.student')),
                ('team', models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='team_scores', to='main.team')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('student__isnull', False), ('team__isnull', False), _connector='OR'), name='student_or_team_required')],
            },
        ),
    ]
