# Generated by Django 5.1.6 on 2025-11-05 13:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_student_age_in_year_student_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='market',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='team',
            name='is_3pt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='is_fix_alloc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='is_mmf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='sim_team_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='simulation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='team_simulation', to='main.simulation'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ImportFileLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('remarks', models.CharField(max_length=5000, unique=True)),
                ('total_row', models.IntegerField(default=0)),
                ('total_insert', models.IntegerField(default=0)),
                ('total_update', models.IntegerField(default=0)),
                ('total_not_found', models.IntegerField(default=0)),
                ('total_duplicate_found', models.IntegerField(default=0)),
                ('creation_date_time', models.DateTimeField(auto_now_add=True)),
                ('modification_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_file_log_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_file_log_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
