# Generated by Django 5.1.6 on 2025-11-20 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_importfilelog_simulation2survey_alter_market_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation2survey',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='student_simulation2_survey', to='main.student'),
        ),
        migrations.AlterField(
            model_name='simulation2survey',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='team_simulation2_survey', to='main.team'),
        ),
        migrations.AlterField(
            model_name='simulation2survey',
            name='team_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='team_member_simulation2_survey', to='main.teammember'),
        ),
    ]
