# Generated by Django 5.1.6 on 2025-10-16 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_simulation_simulationcompetition_simulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationcompetition',
            name='simulation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='simulation', to='main.simulation'),
            preserve_default=False,
        ),
    ]
