# Generated by Django 5.1.6 on 2025-11-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_market_options_team_is_3pt_team_is_fix_alloc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importfilelog',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='importfilelog',
            name='remarks',
            field=models.CharField(max_length=5000),
        ),
    ]
