# Generated by Django 5.1.6 on 2025-11-20 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_simulation2survey_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentscore',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='student_scores', to='main.student'),
        ),
        migrations.AlterField(
            model_name='studentscore',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='team_scores', to='main.team'),
        ),
        migrations.AlterField(
            model_name='studentscore',
            name='team_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='team_member_scores', to='main.teammember'),
        ),
    ]
