# Generated by Django 5.1.6 on 2025-11-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_studentscore_student_alter_studentscore_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation2survey',
            name='row_number',
            field=models.IntegerField(default=0),
        ),
    ]
