# Generated by Django 5.1.6 on 2025-11-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_importfilelog_name_alter_importfilelog_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_id',
            new_name='teamID',
        ),
        migrations.AddField(
            model_name='teammember',
            name='teammember_order',
            field=models.IntegerField(default=0),
        ),
    ]
