# Generated by Django 5.1.6 on 2025-10-16 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_simulationcompetition_simulation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentscore',
            name='simulation_competition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='scores', to='main.simulationcompetition'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='studentscore',
            constraint=models.UniqueConstraint(fields=('student', 'simulation_competition'), name='unique_student_simulation_competition'),
        ),
    ]
