# Generated by Django 5.1.6 on 2025-11-27 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_simulation2survey_row_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation2survey',
            name='statoverall_indiv',
        ),
        migrations.RemoveField(
            model_name='simulation2survey',
            name='statoverall_team',
        ),
    ]
