# Generated by Django 5.1.6 on 2025-11-12 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_team_id_team_teamid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentscore',
            name='team_member',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='team_member_scores', to='main.teammember'),
        ),
        migrations.AlterField(
            model_name='studentscore',
            name='student',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='student_scores', to='main.student'),
            preserve_default=False,
        ),
    ]
