# Generated by Django 5.1.6 on 2025-11-12 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_studentscore_team_member_alter_studentscore_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentscore',
            name='go_venture_subscription_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='studentscore',
            constraint=models.UniqueConstraint(fields=('student', 'market'), name='unique_student_market'),
        ),
    ]
