# Generated by Django 5.1.6 on 2025-11-12 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_studentscore_go_venture_subscription_key_and_more'),
    ]

    operations = [
    ]
