# Generated by Django 5.1.6 on 2026-01-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_simulation3survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='operation_year',
            field=models.IntegerField(default=0),
        ),
    ]
