# Generated by Django 5.1.6 on 2025-11-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20251112_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentscore',
            name='tutorial_quiz_percentage1',
            field=models.IntegerField(null=True),
        ),
    ]
