# Generated by Django 5.1.6 on 2026-01-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_systemsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='id',
            field=models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False),
        ),
    ]
