# Generated by Django 5.1.6 on 2025-11-12 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_studentscore_tutorial_quiz_percentage1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentscore',
            name='tutorial_quiz_percentage1',
        ),
    ]
