# Generated by Django 5.1.6 on 2026-01-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_systemsettings_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='operation_year',
            field=models.IntegerField(default=0),
        ),
    ]
