# Generated by Django 5.1.6 on 2025-11-13 16:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_studentscore_tutorial_quiz_percentage1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation2Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indiv_time_spent', models.IntegerField(default=0)),
                ('joint_time_spent', models.IntegerField(default=0)),
                ('days_in_person', models.IntegerField(default=0)),
                ('responsib_clear', models.IntegerField(default=0)),
                ('responsib_own', models.IntegerField(default=0)),
                ('responsib_change', models.IntegerField(default=0)),
                ('areas_change_1', models.IntegerField(default=0)),
                ('areas_change_2', models.IntegerField(default=0)),
                ('areas_change_3', models.IntegerField(default=0)),
                ('areas_change_4', models.IntegerField(default=0)),
                ('areas_change_avg', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('responsib_outside', models.IntegerField(default=0)),
                ('ta_a', models.IntegerField(default=0)),
                ('ta_b', models.IntegerField(default=0)),
                ('ta_c', models.IntegerField(default=0)),
                ('la_a', models.IntegerField(default=0)),
                ('la_b', models.IntegerField(default=0)),
                ('la_c', models.IntegerField(default=0)),
                ('tms_s1', models.IntegerField(default=0)),
                ('tms_s2', models.IntegerField(default=0)),
                ('tms_s3', models.IntegerField(default=0)),
                ('tms_s4', models.IntegerField(default=0)),
                ('tms_s5', models.IntegerField(default=0)),
                ('tms_cred1', models.IntegerField(default=0)),
                ('tms_cred2', models.IntegerField(default=0)),
                ('tms_cred3', models.IntegerField(default=0)),
                ('tms_cred4', models.IntegerField(default=0)),
                ('tms_cred5', models.IntegerField(default=0)),
                ('tms_co1', models.IntegerField(default=0)),
                ('tms_co2', models.IntegerField(default=0)),
                ('tms_co3', models.IntegerField(default=0)),
                ('tms_co4', models.IntegerField(default=0)),
                ('tms_co5', models.IntegerField(default=0)),
                ('tms_avg', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('att_market_sales', models.IntegerField(default=0)),
                ('att_production', models.IntegerField(default=0)),
                ('att_randd', models.IntegerField(default=0)),
                ('focus_shift_1', models.IntegerField(default=0)),
                ('focus_shift_2', models.IntegerField(default=0)),
                ('focus_shift_3', models.IntegerField(default=0)),
                ('focus_shift_4', models.IntegerField(default=0)),
                ('focus_shift_avg', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('compet_import1', models.IntegerField(default=0)),
                ('compet_import2', models.IntegerField(default=0)),
                ('compet_import3', models.IntegerField(default=0)),
                ('compet_import_avg', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('pcs_1', models.IntegerField(default=0)),
                ('pcs_2', models.IntegerField(default=0)),
                ('pcs_3', models.IntegerField(default=0)),
                ('pcs_avg', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('comments', models.CharField(max_length=1000)),
                ('mail_confirm', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('statoverall_1', models.IntegerField(default=0)),
                ('statoverall_2', models.IntegerField(default=0)),
                ('statoverall_3', models.IntegerField(default=0)),
                ('statoverall_4', models.IntegerField(default=0)),
                ('statoverall_5', models.IntegerField(default=0)),
                ('statoverall_avg', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('creation_date_time', models.DateTimeField(auto_now_add=True)),
                ('modification_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Simulation2Survey_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Simulation2Survey_modified', to=settings.AUTH_USER_MODEL)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='simulation_simulation2_survey', to='main.simulation')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='student_simulation2_survey', to='main.student')),
            ],
        ),
    ]
