# Generated by Django 5.1.6 on 2026-01-27 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_student_operation_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulation',
            old_name='operation_year',
            new_name='academic_year',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='market_member_num',
            new_name='academic_year',
        ),
        migrations.RenameField(
            model_name='systemsettings',
            old_name='active_operation_year',
            new_name='active_academic_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='operation_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='simulation_number',
        ),
    ]
