# Generated by Django 5.1.6 on 2026-01-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_operation_year_simulation_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='is_mmf',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
