# Generated by Django 5.1.6 on 2026-01-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_team_is_mmf'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
