# Generated by Django 5.1.6 on 2026-02-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_simulation_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='market',
            options={'ordering': ['name'], 'verbose_name_plural': '4. Market'},
        ),
        migrations.AlterModelOptions(
            name='simulation',
            options={'verbose_name_plural': '3. Simulation'},
        ),
        migrations.AlterModelOptions(
            name='simulation2survey',
            options={'verbose_name_plural': '8. Simulation2Survey'},
        ),
        migrations.AlterModelOptions(
            name='simulation3survey',
            options={'verbose_name_plural': '9. Simulation3Survey'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '2. Student'},
        ),
        migrations.AlterModelOptions(
            name='studentscore',
            options={'verbose_name_plural': '7. StudentScore'},
        ),
        migrations.AlterModelOptions(
            name='systemsettings',
            options={'verbose_name_plural': '1. SystemSettings'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': '5. Team'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name_plural': '6. TeamMember'},
        ),
        migrations.AddField(
            model_name='student',
            name='exam_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
